#pragma once

#include <stdint.h>

// Generated by the PartGo calibration console. Do not edit by hand.
constexpr char CALIBRATION_ID[] = "sha256:cc1c95986974daccbf755497cff7d538567dadf5f3a38973d9f94a4cfc739ef8";
constexpr uint32_t X_PULSES_PER_MM = 20000;
constexpr uint32_t E_PULSES_PER_MM = 250;
constexpr uint32_t E_SCALE_DIVISOR = 49;
constexpr int32_t E_DOCK_UM = 48000;
constexpr int32_t X_HOOK_SHIFT_UM = 5200;
constexpr int32_t S01_X_UM = 29800;
constexpr int32_t S02_X_UM = 105000;

// Logical positive X is right; logical positive E is extension toward a box.
constexpr bool X_DIR_HIGH_MOVES_RIGHT = true;
constexpr bool E_DIR_HIGH_EXTENDS = true;
