#pragma once

#include <stdint.h>

// Generated by scripts/calibration_server.py after physical calibration.
// Unknown values keep the production controller in CONFIG_LOCKED.
constexpr uint32_t X_PULSES_PER_MM = 20000;
constexpr uint32_t E_PULSES_PER_MM = 0;
constexpr int32_t E_DOCK_UM = -1;
constexpr int32_t S01_X_UM = -1;
constexpr int32_t S02_X_UM = -1;

// Logical positive X is right; logical positive E is extension toward a box.
constexpr bool X_DIR_HIGH_MOVES_RIGHT = true;
constexpr bool E_DIR_HIGH_EXTENDS = false;
