#pragma once

#include <stdint.h>

// Generated by the PartGo calibration console. Do not edit by hand.
constexpr uint32_t X_PULSES_PER_MM = 20000;
constexpr uint32_t E_PULSES_PER_MM = 21;
constexpr uint32_t E_SCALE_DIVISOR = 4;
constexpr int32_t E_DOCK_UM = 48000;
constexpr int32_t X_HOOK_SHIFT_UM = 4500;
constexpr int32_t S01_X_UM = 31700;
constexpr int32_t S02_X_UM = 106000;

// Logical positive X is right; logical positive E is extension toward a box.
constexpr bool X_DIR_HIGH_MOVES_RIGHT = true;
constexpr bool E_DIR_HIGH_EXTENDS = true;
